### ISSUE TITLE
ZMBE 

### ISSUE THREAD

**Issue by AdrianShepard** [TotallyMehis/ZM-AI#1]
Will this AI work on Zombie master: Black edition ?

**Comment by TotallyMehis** [comment]
Probably not.

**Comment by AdrianShepard** [comment]
@TotallyMehis thanks for answearing, if it's not hard to make a version for ZMBE then do you mind making a version special for ZMBE,maybe that way you can ressurect it.

**Comment by TotallyMehis** [comment]
I have no interest in making a version for ZMBE, sorry.

**Comment by AdrianShepard** [comment]
@TotallyMehis That's alright, your plugin is just awesome at what's it doing right now , thanks again for answearing.
